name: CodeQuality Dynamic Code Analysis Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get update
        sudo apt-get -y install valgrind --fix-missing
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev --fix-missing
    - name: make test
      run: make -C 3_Implementation/src test
    - name: Valgrid
      run: valgrind ./3_Implementation/src/test.out
